print("HELLO!")
print(7/4)
print(7//4)
print(3/7)
print(3//7)
#p= int(input("분자를 입력하시오:"))
#q=int (input("분모를 입력하시오:"))
#print("나눗셈의 몫=",p//q)
#print("나눗셈의 나머지",p%q)
#number=int(input("정수를 입력하시오:"))
#print(number%2)
